import { RankEnum } from "./rankEnum";

export const ICONS_BASE_PATH = '../../assets/tier-icons/tier-icons/';

export const ICON_PATHS = {
    bronzeI: `${ICONS_BASE_PATH}bronze_i.png`,
    bronzeII: `${ICONS_BASE_PATH}bronze_ii.png`,
    bronzeIII: `${ICONS_BASE_PATH}bronze_iii.png`,
    bronzeIV: `${ICONS_BASE_PATH}bronze_iv.png`,
    bronzeV: `${ICONS_BASE_PATH}bronze_v.png`,
    silverI: `${ICONS_BASE_PATH}silver_i.png`,
    silverII: `${ICONS_BASE_PATH}silver_ii.png`,
    silverIII: `${ICONS_BASE_PATH}silver_iii.png`,
    silverIV: `${ICONS_BASE_PATH}silver_iv.png`,
    silverV: `${ICONS_BASE_PATH}silver_v.png`,
    goldI: `${ICONS_BASE_PATH}gold_i.png`,
    goldII: `${ICONS_BASE_PATH}gold_ii.png`,
    goldIII: `${ICONS_BASE_PATH}gold_iii.png`,
    goldIV: `${ICONS_BASE_PATH}gold_iv.png`,
    goldV: `${ICONS_BASE_PATH}gold_v.png`,
    platinumI: `${ICONS_BASE_PATH}platinum_i.png`,
    platinumII: `${ICONS_BASE_PATH}platinum_ii.png`,
    platinumIII: `${ICONS_BASE_PATH}platinum_iii.png`,
    platinumIV: `${ICONS_BASE_PATH}platinum_iv.png`,
    platinumV: `${ICONS_BASE_PATH}platinum_v.png`,
    diamondI: `${ICONS_BASE_PATH}diamond_i.png`,
    diamondII: `${ICONS_BASE_PATH}diamond_ii.png`,
    diamondIII: `${ICONS_BASE_PATH}diamond_iii.png`,
    diamondIV: `${ICONS_BASE_PATH}diamond_iv.png`,
    diamondV: `${ICONS_BASE_PATH}diamond_v.png`,
    esmeraldI: `${ICONS_BASE_PATH}esmerald_i.png`,
    esmeraldII: `${ICONS_BASE_PATH}esmerald_ii.png`,
    esmeraldIII: `${ICONS_BASE_PATH}esmerald_iii.png`,
    esmeraldIV: `${ICONS_BASE_PATH}esmerald_iv.png`,
    esmeraldV: `${ICONS_BASE_PATH}esmerald_v.png`,
    master: `${ICONS_BASE_PATH}master.png`,
    challenger: `${ICONS_BASE_PATH}challenger.png`,
    provisional: `${ICONS_BASE_PATH}provisional.png`,
  };

 export const rankIconMap = {
    [RankEnum.BRONZE_I]: ICON_PATHS.bronzeI,
    [RankEnum.BRONZE_II]: ICON_PATHS.bronzeII,
    [RankEnum.BRONZE_III]: ICON_PATHS.bronzeIII,
    [RankEnum.BRONZE_IV]: ICON_PATHS.bronzeIV,
    [RankEnum.BRONZE_V]: ICON_PATHS.bronzeV,
    [RankEnum.SILVER_I]: ICON_PATHS.silverI,
    [RankEnum.SILVER_II]: ICON_PATHS.silverII,
    [RankEnum.SILVER_III]: ICON_PATHS.silverIII,
    [RankEnum.SILVER_IV]: ICON_PATHS.silverIV,
    [RankEnum.SILVER_V]: ICON_PATHS.silverV,
    [RankEnum.GOLD_I]: ICON_PATHS.goldI,
    [RankEnum.GOLD_II]: ICON_PATHS.goldII,
    [RankEnum.GOLD_III]: ICON_PATHS.goldIII,
    [RankEnum.GOLD_IV]: ICON_PATHS.goldIV,
    [RankEnum.GOLD_V]: ICON_PATHS.goldV,
    [RankEnum.PLATINUM_I]: ICON_PATHS.platinumI,
    [RankEnum.PLATINUM_II]: ICON_PATHS.platinumII,
    [RankEnum.PLATINUM_III]: ICON_PATHS.platinumIII,
    [RankEnum.PLATINUM_IV]: ICON_PATHS.platinumIV,
    [RankEnum.PLATINUM_V]: ICON_PATHS.platinumV,
    [RankEnum.DIAMOND_I]: ICON_PATHS.diamondI,
    [RankEnum.DIAMOND_II]: ICON_PATHS.diamondII,
    [RankEnum.DIAMOND_III]: ICON_PATHS.diamondIII,
    [RankEnum.DIAMOND_IV]: ICON_PATHS.diamondIV,
    [RankEnum.DIAMOND_V]: ICON_PATHS.diamondV,
    [RankEnum.EMERALD_I]: ICON_PATHS.esmeraldI,
    [RankEnum.EMERALD_II]: ICON_PATHS.esmeraldII,
    [RankEnum.EMERALD_III]: ICON_PATHS.esmeraldIII,
    [RankEnum.EMERALD_IV]: ICON_PATHS.esmeraldIV,
    [RankEnum.EMERALD_V]: ICON_PATHS.esmeraldV,
    [RankEnum.PROVISIONAL]: ICON_PATHS.provisional,
    [RankEnum.MASTERI]: ICON_PATHS.master,
    [RankEnum.CHALLENGERI]: ICON_PATHS.challenger,
  };

 export type Tier = 'bronzeI' | 'bronzeII' | 'bronzeIII' | 'bronzeIV' | 'bronzeV' | 'silverI' | 'silverII' | 'silverIII' | 'silverIV' | 'silverV' | 'goldI' | 'goldII' | 'goldIII' | 'goldIV' | 'goldV' | 'platinumI' | 'platinumII' | 'platinumIII' | 'platinumIV' | 'platinumV' | 'diamondI' | 'diamondII' | 'diamondIII' | 'diamondIV' | 'diamondV';